<a href="https://colab.research.google.com/github/TanyaKumari0204/Machine-Learning/blob/main/Matrix1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Dot product

In [ ]:
a=np.asarray([2,3])
b=np.asarray([3,4])
a_dot_b=np.dot(a,b)
print(a_dot_b)


18


In [ ]:
c=np.asarray([40,20,35])
d=np.asarray([53,24,68])
c_dot_d=np.dot(c,d)
print(c_dot_d)

4980


Cross Product of two vectors:-

In [ ]:
a=np.asarray([2,3])
b=np.asarray([3,4])
a_cross_b=np.cross(a,b)
print(a_cross_b)


-1


/tmp/ipython-input-4-2658644620.py:3: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  a_cross_b=np.cross(a,b)


In [ ]:
c=np.asarray([40,20,35])
d=np.asarray([53,24,68])
c_cross_d=np.cross(c,d)
print(c_cross_d)


[ 520 -865 -100]


Projection
:-

In [ ]:
a=np.array([2,5])
v=np.array([8,-6])
magnitude_of_v=np.sqrt(sum(v**2))#under rooot v1 sq and v2 sq
proj_of_a_on_v=(np.dot(a,v)/magnitude_of_v**2)*v
print(proj_of_a_on_v)


[-1.12  0.84]


In [ ]:
a=np.array([23,45,67])
v=np.array([8,-6,56])
magnitude_of_v=np.sqrt(sum(v**2))#under rooot v1 sq and v2 sq
proj_of_a_on_v=(np.dot(a,v)/magnitude_of_v**2)*v
print(proj_of_a_on_v)


[ 9.06304079 -6.79728059 63.44128554]


Creating matrix using numpy

In [ ]:
matrix_1=np.array([[2,3],[3,4]])
print(matrix_1)

[[2 3]
 [3 4]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2=np.array([[2,3,4],[5,6,7],[7,8,9]])
print(matrix_2)
matrix_2.shape

[[2 3 4]
 [5 6 7]
 [7 8 9]]


(3, 3)

Create matrix with random values:-

In [ ]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.61650282 0.80817887 0.52094442]
 [0.89889609 0.78441506 0.13515849]
 [0.769417   0.64680327 0.9164015 ]]


In [ ]:
random_matrix_int=np.random.randint(1,10,size=(3,3))
print(random_matrix_int)

[[9 1 7]
 [5 5 9]
 [3 3 5]]


In [ ]:
#Value all set to 1
matrix_3=np.ones((3,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix=np.ones((3,3),dtype=int)
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#Null matrix:-
null_matrix=np.zeros((3,3))
print(null_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
null=np.zeros((3,3),dtype=int)
print(null)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#Identity Matrix:-
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose

In [ ]:
mat=np.random.randint(1,10,size=(3,3))
transpose=mat.transpose()
print(transpose)
print(mat)

[[9 6 1]
 [4 6 8]
 [1 7 8]]
[[9 4 1]
 [6 6 7]
 [1 8 8]]


Matrix addition:-


In [ ]:
A=np.array([[2,3],[4,5]])
B=np.array([[4,5,],[5,6]])
print(A)
print(B)
A.shape
B.shape
sum=A+B
print(sum)



[[2 3]
 [4 5]]
[[4 5]
 [5 6]]
[[ 6  8]
 [ 9 11]]


In [ ]:
X=np.random.randint(1,10,size=(3,3))
Y=np.random.randint(1,10,size=(3,3))
print(X)
print(Y)
add=np.add(X,Y)
print(add)

[[2 6 8]
 [7 6 5]
 [6 3 6]]
[[9 9 3]
 [5 2 7]
 [3 2 1]]
[[11 15 11]
 [12  8 12]
 [ 9  5  7]]


Matrix Subtraction:-

In [ ]:
A=np.array([[2,3],[4,5]])
B=np.array([[4,5,],[5,6]])
print(A)
print(B)
A.shape
B.shape
diff=A-B
print(diff)

[[2 3]
 [4 5]]
[[4 5]
 [5 6]]
[[-2 -2]
 [-1 -1]]


In [ ]:
X=np.random.randint(1,10,size=(3,3))
Y=np.random.randint(1,10,size=(3,3))
print(X)
print(Y)
sub=np.subtract(X,Y)
print(sub)

[[1 5 5]
 [1 3 7]
 [8 1 8]]
[[2 6 6]
 [2 8 3]
 [2 7 8]]
[[-1 -1 -1]
 [-1 -5  4]
 [ 6 -6  0]]


Multiplying Matrix:-

In [ ]:
x=5
A=np.random.randint(1,10,size=(3,3))
print(A)
mul=np.multiply(x,A)
print(mul)

[[6 3 9]
 [9 9 7]
 [5 5 9]]
[[30 15 45]
 [45 45 35]
 [25 25 45]]


In [ ]:
A=np.random.randint(1,10,size=(3,4))#col of 1st should be same to row of 2nd
B=np.random.randint(1,10,size=(4,3))
product=np.dot(A,B)
product.shape

(3, 3)

In [ ]:
#Element wise mul
A=np.random.randint(1,10,size=(3,3))
B=np.random.randint(1,10,size=(3,3))
print(A)
print(B)
product=np.multiply(A,B)
print(product)

[[4 4 4]
 [5 6 5]
 [3 4 6]]
[[7 3 2]
 [3 9 9]
 [5 5 5]]
[[28 12  8]
 [15 54 45]
 [15 20 30]]
