<a href="https://colab.research.google.com/github/TanyaKumari0204/Machine-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numerical python

In [ ]:
import numpy as np


list vs nump

In [ ]:
from time import process_time

In [ ]:
#by list
list=[i for i in range(10000)]
start_time=process_time()
list=[i+5 for i in list]
end_time=process_time()
print(end_time-start_time)


0.0008103410000011024


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0007979969999993841


Numpy Arrays

In [ ]:
list1=[1,2,3,4]
print(list1)
type(list1)

np_array=np.array([1,2,3,4])
print(np_array)
type(np_array)

[1, 2, 3, 4]
[1 2 3 4]


numpy.ndarray

In [ ]:
#1 d array
a=np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [ ]:
#2d array
a=np.array([(1,2,3,4),(7,8,9,0)])
print(a)
a.shape

[[1 2 3 4]
 [7 8 9 0]]


(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
#initial placeholder
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z=np.full((5,4),7)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#identity matrix dia 1,other 0
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
n=np.random.random((3,4))#3,4 is shape of matrix
print(n)

[[0.6096046  0.86146034 0.02155929 0.2785553  0.31555787]
 [0.11400772 0.44299293 0.22516075 0.76750302 0.24967485]
 [0.87730693 0.95009886 0.17256476 0.78692209 0.7682128 ]]


In [ ]:
#random int value
r=np.random.randint(10,100,(3,4))#10,100 is int range and 3,4 is size of matrix
print(r)

[[59 88 37 19]
 [16 33 18 29]
 [27 80 16 39]]


In [ ]:
#array of evenly spaced
d=np.linspace(10,30,5)#5 values evenly spaced beten 10,35
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
e=np.arange(10,30,5)#here 5 is steps ,not 5 values
print(e)

[10 15 20 25]


In [ ]:
#list to numpy array
list=[1,2,3,44]
np_array=np.asarray(list)
print(np_array)
type(np_array)

[ 1  2  3 44]


numpy.ndarray

In [ ]:
tup=(1,2,3,4)
np_array=np.asarray(tup)
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

Analysing numpy array:-

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)
print(c.shape)


[[14 17 64 59 86]
 [35 77 45 81 88]
 [75 67 26 49 26]
 [34 34 54 36 49]
 [71 33 27 61 56]]
(5, 5)


In [ ]:
#number of dimension
print(c.ndim)

2


In [ ]:
#no.of elementd
print(c.size)

25


In [ ]:
#check data type of array
print(c.dtype)

int64


Mathematical operations:-


In [ ]:
list1=[12,3,4]
list2=[2,3,4,5]
list=list1+list2#it concatenate ,not do elemnts wise addn
print(list)

[12, 3, 4, 2, 3, 4, 5]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 3 0]
 [6 0 3]
 [3 4 2]]
[[17 10 17]
 [13 13 12]
 [18 17 19]]


In [ ]:
print(a+b)#element wise addn

[[22 13 17]
 [19 13 15]
 [21 21 21]]


In [ ]:
print(np.add(a,b))

[[22 13 17]
 [19 13 15]
 [21 21 21]]


In [ ]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[-12  -7 -17]
 [ -7 -13  -9]
 [-15 -13 -17]]
[[85 30  0]
 [78  0 36]
 [54 68 38]]
[[0.29411765 0.3        0.        ]
 [0.46153846 0.         0.25      ]
 [0.16666667 0.23529412 0.10526316]]


Array Manipulation:-

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 3 9]
 [8 6 4]]
(2, 3)


In [ ]:
trans=np.transpose(array)
print(trans)

[[9 8]
 [3 6]
 [9 4]]


In [ ]:
print(trans.shape)

(3, 2)


In [ ]:
trans2=array.T
print(trans2)
trans2.shape


[[9 8]
 [3 6]
 [9 4]]


(3, 2)

In [ ]:
#reshape array:-
a=np.random.randint(0,10,(6,2))
print(a)
a.shape
b=a.reshape(4,3)
print(b)
b.shape


[[5 5]
 [6 8]
 [0 0]
 [0 0]
 [1 7]
 [8 4]]
[[5 5 6]
 [8 0 0]
 [0 0 1]
 [7 8 4]]


(4, 3)